linuxdeepin/dde-app-services

dconfig-center/common/valuehandler.cpp, dconfig-center/dde-dconfig-daemon/dconfigconn.cpp, dconfig-center/dde-dconfig-editor/CMakeLists.txt, dconfig-center/dde-dconfig-editor/appicon/dde-dconfig-editor.svg, dconfig-center/dde-dconfig-editor/dde-dconfig-editor.qrc, dconfig-center/dde-dconfig-editor/main.cpp, dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig-editor/mainwindow.h
读取value时，判断value值是否为空；
如果value值为空，发送错误，返回默认值。
Log: 修复dconfig-editor读取没有value值的项时会卡住
Bug: https://pms.uniontech.com/bug-view-144233.html
Influence: dde-dconfig-editor读取没有value值的项
Change-Id: Iec8f00e587bbad28f661d4c26b1ddbb20a183676
=> fix: dconfig-editor读取没有value值的项时会卡住

dconfig-center/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/CMakeLists.txt, dconfig-center/dde-dconfig-editor/CMakeLists.txt, dconfig-center/dde-dconfig/CMakeLists.txt
Log: use GNUInstallDirs in CmakeLists
relate:https://github.com/linuxdeepin/developer-center/issues/3167
=> chore: use GNUInstallDirs in CmakeLists

debian/rules
空格改成Tab
Log:
Influence: deb package
Change-Id: I5965c1c8e165ff78adaeb617efef8e78fd73e630
=> chore: rules文件格式错误

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigrefmanager.cpp, dconfig-center/dde-dconfig-daemon/dconfigrefmanager.h, dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/dconfigresource.h, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.h, dconfig-center/tests/ut_dconfigrefmanager.cpp
It's to reduce the risk caused by abnormality.
We start a sync request when every connection call setValue(),
and lay sync time is 30s, batch max count is 10 for when sync.
TODO We can use queue or other scheduling mechanism if necessary.
Log: 将缓存定期同步到文件中，减少因异常丢失数据风险
Influence: cache文件由之前连接关闭同步 改为 延时30s同步
Change-Id: Ib1eb387b181d2aca6588f899c5538f134123a61b
=> feat: Add sync2file when setValue

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/tests/ut_dconfigserver.cpp
RegularExpression can't parse meta file that path contains '.'
Log: 配置中心服务调用sync接口路径解析错误
Change-Id: Id544b5e7518a5f399feca108a25989b0b9216852
=> fix: path parse error of meta file

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigconn.cpp, dconfig-center/dde-dconfig-daemon/dconfigconn.h, dconfig-center/dde-dconfig-daemon/dconfigrefmanager.h, dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/dconfigresource.h, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.h, dconfig-center/tests/ut_dconfigconn.cpp, dconfig-center/tests/ut_dconfigserver.cpp
Redefining same resource from `/appid/filename/subpath` to
`/filename/subpath`, it causes that DSGConfigResource manage more Connection, including different `uid` or `appid`.
DSGConfigResource manages all Connection, ConfigFile and
ConfigCache.
DSGConfigConnection doesn't manage ConfigCache, it only access
Config by resouce's function.
Log: 重构daemon的链接管理结构
Change-Id: Ica3e5e11f303b74b12c4cf58d7bd3a356194767a
=> refactor: Refactor dde-dconfig to support interapp config

dconfig-center/common/helper.hpp, dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigconn.cpp, dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/dconfigresource.h, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig/main.cpp, dconfig-center/example/main.cpp, dconfig-center/tests/ut_dconfigconn.cpp, dconfig-center/tests/ut_dconfigserver.cpp, debian/control
fallback to generic configuration if application is not changed,
and if generic configuration is changed, it will emit all related application's valueChanged.
Log: none
Change-Id: I90ad3bf631f69eb93445212a5cb6fab1c4ad1ec7
=> feat: Support empty appid as interapp configure

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigconn.cpp, dconfig-center/dde-dconfig-daemon/dconfigrefmanager.cpp, dconfig-center/dde-dconfig-daemon/dconfigrefmanager.h, dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.h, dconfig-center/dde-dconfig-daemon/main.cpp
Modify log format.
Call `exit` to clean resource when exiting.
=> fix: Cleaning resource When exiting manual

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp
resources's key is GenericResourceKey instead of ResourceKey.
=> fix: Save cache invalided

dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/main.cpp, debian/control
Relocate cache's position to dde-dconfig-daemon's home dir.
It can remove dde-dconfig-daemon's root permission.
Log: 重定位缓存位置，以便能够移除dde-dconfig-daemon必须的root权限
Issue: https://github.com/linuxdeepin/dtkcore/issues/271
=> feat: Relocate cache position

dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.conf, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.service, debian/postinst
Don't run dbus service by root
Log: Everybody is allowed to own the service on the D-Bus system bus.
=> fix: fix security issue

dconfig-center/CMakeLists.txt, dconfig-center/dde-dconfig-editor/CMakeLists.txt, dconfig-center/dde-dconfig/main.cpp, debian/changelog
1. update to 1.0.20 (gerrit/dde-app-services 1.0.19.2 ...)
2. dde-dconfig use VERSION application version
=> chore: update version to 1.0.20

dconfig-center/dde-dconfig-daemon/main.cpp
We shouldn't use signal for param of`QCoreApplication::exit()`
=> fix: Wrong exit signal

dconfig-center/dde-dconfig-daemon/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon.service, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.service, debian/dde-dconfig-daemon.install
Add systemd service to set `DSG_DATA_DIRS` for dde-dconfig-daemon.
It resoved that `linglong` applications can't access DConfig.
Issue: https://github.com/linuxdeepin/developer-center/issues/4161
=> feat: Add systemd service

dconfig-center/dde-dconfig-daemon/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon-tmpfiles.conf, dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon.conf, debian/dde-dconfig-daemon.sysusers, debian/dde-dconfig-daemon.tmpfiles, debian/postinst, debian/rules
We have been used systemd, so we can use sysusers.d to manage
it's users and tmpfiles.d to manage homedir.
postinst can't remove added user when uninstall, and it's
permissions also has some incorrectly.
In debian, debian/dde-dconfig-daemon.sysusers is useful, user is
not created when install firstly even if conf is installed in
sysusers.d, we need reload systemd-sysusers manually.
debian/dde-dconfig-daemon.sysusers is a hard link, and we should
override dh_auto_install, otherwise, `sysusers` is declaraed before
`tmpfiles` because user mentioned in tmpfiles.
=> feat: Manage user by sysusers.d to replace postinst

dconfig-center/common/helper.hpp, debian/control
`dde-dconfig` and `dde-dconfig-editor` have hard code for metadir,
now we replace it with dtkcore's interface.
Issue: https://github.com/linuxdeepin/dtk/issues/10
=> feat: Being consistent with dtkcore for meta dir

dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.h, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.xml, dconfig-center/example/dbus-dconfig.sh
For the convenience of debugging, we use QLoggingCategory::
setFilterRules to change log's rules.
=> feat: Support runtime control of verbose log on/off switch

CMakeLists.txt, dconfig-center/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/src.cmake, dconfig-center/dde-dconfig-editor/CMakeLists.txt, dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig/CMakeLists.txt, dconfig-center/example/CMakeLists.txt, dconfig-center/tests/CMakeLists.txt, debian/rules
Adapt to cmake.
Issue: https://github.com/linuxdeepin/dtk/issues/86
=> chore: Adapt to qt6

dconfig-center/common/helper.hpp
Don't check appid is exist for `dde-dconfig`, and it's useful
for application-independent configuration.
=> Fix: Set function invalid when appid is not exist

dconfig-center/dde-dconfig-editor/mainwindow.cpp
Only positive value for `min()`
=> fix: Wrong value for negative float type in editor

dconfig-center/dde-dconfig-editor/exportdialog.cpp, dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig/bash_completion.d/dde-dconfig, dconfig-center/dde-dconfig/main.cpp, dconfig-center/example/dde-dconfig.sh
Support positional argument for dde-dconfig.
resourceid's value falling back to appid if `-r` is empty.
Add some help information.
Modify commander's struct, using class instead of function.
=> feat: Support positional argument for dde-dconfig

dconfig-center/dde-dconfig-daemon/main.cpp
=> chore: Can't find QCommandLineParser

dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig-editor/mainwindow.h
Sync value from ConfigGetter to UI when setValue.
Fallback displayName and description to default language.
Only refresh the item's content when reset.
=> feat: Sync setValue for dde-dconfig-editor

dconfig-center/dde-dconfig-daemon/dconfigresource.cpp
It introduced int the commit 0280dc6c951d3664be7c18b2b423084f22279a40
Access invalid itertor.
=> fix: Crashed when repareCache for dde-dconfig-daemon

dconfig-center/dde-dconfig-editor/mainwindow.cpp
ListView's model is nullptr before `resource` selected.
Issue: https://pms.uniontech.com/bug-view-222631.html
=> fix: dde-dconfig-editor crashed

dconfig-center/dde-dconfig-editor/mainwindow.cpp
model need clear when refresh app resources.
it introduced in 6c737db9e9661d158a1c7267424004cf47763b59
=> fix: repeated items for dde-dconfig-editor

dconfig-center/common/helper.hpp, dconfig-center/common/valuehandler.cpp, dconfig-center/common/valuehandler.h, dconfig-center/dde-dconfig-editor/oemdialog.cpp, dconfig-center/example/configs/example.json
It should be decided if the item of OEM is readonly by the flags [nooverride]
Log: fix the item of OEM is readonly by permission field
=> fix: The item of OEM is readonly by permission field

dconfig-center/dde-dconfig-daemon/CMakeLists.txt, dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon-tmpfiles.conf, dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon.service, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.service, debian/dde-dconfig-daemon.tmpfiles, debian/rules
=> chore: systemd hardening

dconfig-center/dde-dconfig-daemon/services/dde-dconfig-daemon.service, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.service
=> fix: dde-dconfig-daemon can't be started by DBus

dconfig-center/common/helper.hpp, dconfig-center/common/valuehandler.cpp, dconfig-center/common/valuehandler.h, dconfig-center/dde-dconfig-editor/mainwindow.cpp, dconfig-center/dde-dconfig-editor/translates/dde-dconfig-editor_zh_CN.ts
We can run dde-dconfig-editor as user A, and read user B's config,
It's only work for config flags contains UserPublic,
some config maybe not read because of permission.
If we want to read user B's config as user B, we only runn
dde-dconfig-editor by user B.
=> feat: support to read other user's config for editor

dconfig-center/dde-dconfig-daemon/dconfig_global.h, dconfig-center/dde-dconfig-daemon/dconfigresource.cpp, dconfig-center/dde-dconfig-daemon/dconfigresource.h, dconfig-center/dde-dconfig-daemon/dconfigserver.cpp, dconfig-center/dde-dconfig-daemon/dconfigserver.h, dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.xml, dconfig-center/docs/DtkConfig.zh_CN.md, dconfig-center/tests/ut_dconfigserver.cpp
1. Added removeUserData method to clean up user-specific configs
2. Implemented configPrefixPath helper function in global header
3. Added getConnectionsByUid to find all connections for a user
4. Updated D-Bus interface definition with new method
5. Added detailed documentation in Chinese manual
6. Includes recursive directory removal for user cache files
The changes enable proper cleanup of user configuration data when
accounts are deleted, preventing stale configs from accumulating. The
implementation handles both in-memory connections and on-disk cache
files while maintaining security through D-Bus policy controls.
feat: 添加用户配置清理功能
1. 添加removeUserData方法清理用户特定配置
2. 在全局头文件中实现configPrefixPath辅助函数
3. 添加getConnectionsByUid查找用户所有连接
4. 更新D-Bus接口定义添加新方法
5. 在中文手册中添加详细文档
6. 包含用户缓存文件的递归目录删除 …
=> feat: add user configuration cleanup functionality
