- LICENSE
add a LGPLv3 license file
Log: add the LGPLv3L license
Influence: license
Change-Id: Iac5b14e4244f2cc44dc99a6c45fdd10cb96439ae
> feat: add the LGPLv3 license

- debian/changelog
modify changelog avoid of error of github's ci.
Log: 修改ci报错
Influence: github's ci error
Change-Id: I2dbcc8e3c748bf4cfe36c9fb62322182b184ba8b
> chore: modify changelog

- README.md
- README.zh_CN.md
add README.mde and README.zh_CN.md
Log: 添加说明文档
Change-Id: I228dc2d0f14834ad9eec8472562e3aa6a9f52caa
> chore: Add readme

- dconfig-center/dde-dconfig-editor/CMakeLists.txt
- dconfig-center/dde-dconfig-editor/main.cpp
- debian/rules
dcoonfig-editor 的应用关于版本号
随着打包的版本号变化而变化
Log: dconfig-editor应用版本号跟随上游打包的版本号
Influence: dconfig-editor 关于
Change-Id: Ied34b81bbdffb8b880d481a7ec645c9604fff5c6
> feat: dconfig-editor的关于版本号跟随上游打包版本号

- dconfig-center/dde-dconfig/bash_completion.d/dde-dconfig
- debian/control
Building error in github for Lintian check.
print `E: dde-dconfig-daemon: shell-script-fails-syntax-check
usr/share/bash-completion/completions/dde-dconfig`.
Log: 打包错误
Change-Id: Ic9900e65dc74bc709b9bcf3b2b5758f6c6b01d62
> fix(build): lintian error

- dconfig-center/dde-dconfig-editor/mainwindow.cpp
spinbox 输入后会清除焦点，体验很差
Log:
Change-Id: I3b6f83e5786ec8fc377df6acd7d0d7ed08bb2968
> chore: 优化使用体验

- dconfig-center/dde-dconfig/CMakeLists.txt
add Qt5::Gui to COMMON_LIBS
Log:
> fix: missing Qt5::Gui

- .gitignore
- dconfig-center/common/helper.hpp
- dconfig-center/dde-dconfig/CMakeLists.txt
Remove Qt5::Gui for dde-dconfig.
Add gitignore's entities.
Log: 
Change-Id: Iae7b1d3b057515c033d42822e6cd91556047ee8c
> fix: Removing Qt5::Gui

- dconfig-center/common/helper.hpp
- dconfig-center/dde-dconfig-editor/mainwindow.cpp
Memory leak.
In order to app list.
Change-Id: I023f8b57bece87053529428f1c59e279b432f8ab
> fix: Memory leak for dconfig-editor

- dconfig-center/dde-dconfig-daemon/dconfig_global.h
- dconfig-center/dde-dconfig-daemon/dconfigresource.cpp
- dconfig-center/dde-dconfig-daemon/dconfigresource.h
- dconfig-center/dde-dconfig-daemon/dconfigserver.cpp
- dconfig-center/dde-dconfig-daemon/dconfigserver.h
- dconfig-center/tests/ut_dconfigserver.cpp
Rename interAppResource to GenericResource
Log: none
Change-Id: I400758749611d0a2703ff36ac85d1ea66dea08a9
> chore: Rename application independed resource

- dconfig-center/dde-dconfig-daemon/dconfigrefmanager.cpp
Reduce sync time by reducing time and increasing batch count.
> fix: Modify delay sync time

- debian/changelog
> chore: bump version to 0.0.23

- debian/changelog
> chore: bump version to 1.0.21

- dconfig-center/dde-dconfig-daemon/dconfig_global.h
- dconfig-center/dde-dconfig-daemon/dconfigconn.cpp
- dconfig-center/dde-dconfig-daemon/dconfigconn.h
Application name is truncated to 15 characters.
Add cache for application name.
> chore: Change the way to get application name

- .obs/workflows.yml
- .reuse/dep5
- archlinux/PKGBUILD
> feat: add PKGBUILD

- dconfig-center/dde-dconfig-daemon/dconfigserver.cpp
> fix: typo refrence to reference

- dconfig-center/dde-dconfig-daemon/dconfig_global.h
Convert some invalid character to '_'.
Log:
> fix: some app failed to register dbus service

- debian/changelog
> chore: Update changelog to 1.0.22

- .reuse/dep5
- dconfig-center/common/helper.hpp
- dconfig-center/dde-dconfig-editor/CMakeLists.txt
- dconfig-center/dde-dconfig-editor/exportdialog.cpp
- dconfig-center/dde-dconfig-editor/main.cpp
- dconfig-center/dde-dconfig-editor/mainwindow.cpp
- dconfig-center/dde-dconfig-editor/oemdialog.cpp
- dconfig-center/dde-dconfig-editor/translates/dde-dconfig-editor_zh_CN.ts
- dconfig-center/dde-dconfig/CMakeLists.txt
- dconfig-center/dde-dconfig/main.cpp
- dconfig-center/dde-dconfig/translates/dde-dconfig_zh_CN.ts
- debian/control
- debian/dde-dconfig-daemon.install
- debian/dde-dconfig-editor.install
Add translation for dde-dconfig and dde-dconfig-editor.
Select system language as default description language.
Issue: https://github.com/linuxdeepin/dtk/issues/66
> feat: Add chinese translation for tools

- debian/changelog
> chore: Update changelog to 1.0.23

- dconfig-center/common/valuehandler.cpp
- dconfig-center/common/valuehandler.h
- dconfig-center/dde-dconfig-daemon/dconfigconn.cpp
- dconfig-center/dde-dconfig-daemon/dconfigconn.h
- dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.Manager.xml
- dconfig-center/dde-dconfig-editor/mainwindow.cpp
- dconfig-center/dde-dconfig-editor/mainwindow.h
- dconfig-center/dde-dconfig/main.cpp
- dconfig-center/dde-dconfig/translates/dde-dconfig_zh_CN.ts
- dconfig-center/docs/org.desktopspec.ConfigManager.Manager.xml
- dconfig-center/example/dbus-dconfig.sh
- dconfig-center/example/dde-dconfig.sh
- dconfig-center/example/main.cpp
- dconfig-center/tests/ut_dconfigconn.cpp
Add isDefaultValue in dde-dconfig-daemon
Add ut and example.
Change label's color to distinguish isDefaultValue in dde-dconfig-editor.
Add method to query isDefaultValue in dde-dconfig.
Issue: https://github.com/linuxdeepin/dtk/issues/3
> feat: Add the way to check value is or not default value

- dconfig-center/dde-dconfig-daemon/dconfigconn.cpp
- dconfig-center/dde-dconfig-daemon/dconfigconn.h
Add the key const to the function getAppid
Log: Add the key const to the function getAppid
> chore: Add the key const to the function getAppid

- dconfig-center/common/valuehandler.cpp
- dconfig-center/common/valuehandler.h
- dconfig-center/dde-dconfig-daemon/dconfigconn.cpp
- dconfig-center/dde-dconfig-daemon/dconfigconn.h
- dconfig-center/dde-dconfig-daemon/dconfigserver.cpp
- dconfig-center/dde-dconfig-daemon/dconfigserver.h
- dconfig-center/dde-dconfig-daemon/services/org.desktopspec.ConfigManager.xml
- dconfig-center/dde-dconfig/main.cpp
- dconfig-center/dde-dconfig/translates/dde-dconfig_zh_CN.ts
- dconfig-center/docs/org.desktopspec.ConfigManager.xml
- dconfig-center/example/CMakeLists.txt
- dconfig-center/example/configs/example.json
- dconfig-center/example/dbus-dconfig.sh
- dconfig-center/example/dde-dconfig.sh
- dconfig-center/tests/ut_dconfigserver.cpp
- debian/control
add acquireManagerV2 interface;
add the unit test of the interface;
update the document;
Issue: https://github.com/linuxdeepin/developer-center/issues/5928
> chore: add acquireManagerV2 interface

- debian/changelog
> chore: bump version to 1.0.24

- dconfig-center/docs/CMakeLists.txt
Use macro instead of hardcord for qhelpgenerator
Log:
> Fix: Don't hardcode qhelpgenerator

- debian/changelog
> chore: update changelog to 1.0.25

- dconfig-center/dde-dconfig/bash_completion.d/dde-dconfig
optimize the bash completion script of dde-dconfig
Log: Optimize the bash completion script
> chore: Optimize the bash completion script

- dconfig-center/dde-dconfig/CMakeLists.txt
- dconfig-center/dde-dconfig/completion/dde-dconfig.bash
- dconfig-center/dde-dconfig/completion/dde-dconfig.zsh
- debian/dde-dconfig-daemon.install
add zsh completion script
Log: add zsh completion script
> chore: add zsh completion script

- dconfig-center/common/helper.hpp
support to list subpath for applications.
> fix: can't get subpath in tools

- debian/changelog
> chore: bump version to 1.0.26

- debian/changelog
> chore: bump version to 1.0.27
